### ISSUE TITLE
你好，请教一下

### ISSUE THREAD

**Issue by xlgosin** [tianyl1984/weixin-robot#1]
你好，我想请教下，刚部署了你的代码。
貌似这个登陆 初始化wxinit的时候，现在已经获取不到用户参数了。
总是提示登陆失败，是微信的接口问题？

**Comment by tianyl1984** [comment]
接口我参考的 https://github.com/Urinx/WeixinBot 项目，改成了java版，昨天测试是可以的

**Comment by xlgosin** [comment]
扫码后，点登陆。
调用的weixin的init方法出了bug。Ret返回了1100，知道是什么原因吗？
Exception in thread "main" com.tianyl.weixin.robot.exception.WeiXinException: weixin init
	at com.tianyl.weixin.robot.web.WeiXin.checkResponse(WeiXin.java:99)
	at com.tianyl.weixin.robot.web.WeiXin.wxinit(WeiXin.java:84)
	at com.tianyl.weixin.robot.web.WeiXin.start(WeiXin.java:58)
	at com.tianyl.weixin.robot.web.WeiXin.main(WeiXin.java:181)

**Comment by tianyl1984** [comment]
刚刚测试一下可以没有问题，你可以在网页中抓包看看
